// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxMShXoPz-C-9k6Dhtzk8P74b1C5ddEsg',
    appId: '1:466963417642:web:884922d83aa7b85f349153',
    messagingSenderId: '466963417642',
    projectId: 'youth-camp-icmc-2025',
    authDomain: 'youth-camp-icmc-2025.firebaseapp.com',
    storageBucket: 'youth-camp-icmc-2025.firebasestorage.app',
    measurementId: 'G-EZVP8KJ6GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtVyvGwx-f8ef5Y9RlNGpHMcUKQK-nww',
    appId: '1:466963417642:android:ef0686e537f24a13349153',
    messagingSenderId: '466963417642',
    projectId: 'youth-camp-icmc-2025',
    storageBucket: 'youth-camp-icmc-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUT8nx0PVKq3qqj8HWV6Qbdj9KBS9sAcs',
    appId: '1:466963417642:ios:653b5f7983ef94a9349153',
    messagingSenderId: '466963417642',
    projectId: 'youth-camp-icmc-2025',
    storageBucket: 'youth-camp-icmc-2025.firebasestorage.app',
    iosBundleId: 'com.example.ycIcmc2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUT8nx0PVKq3qqj8HWV6Qbdj9KBS9sAcs',
    appId: '1:466963417642:ios:653b5f7983ef94a9349153',
    messagingSenderId: '466963417642',
    projectId: 'youth-camp-icmc-2025',
    storageBucket: 'youth-camp-icmc-2025.firebasestorage.app',
    iosBundleId: 'com.example.ycIcmc2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxMShXoPz-C-9k6Dhtzk8P74b1C5ddEsg',
    appId: '1:466963417642:web:2216cda50b2fd47d349153',
    messagingSenderId: '466963417642',
    projectId: 'youth-camp-icmc-2025',
    authDomain: 'youth-camp-icmc-2025.firebaseapp.com',
    storageBucket: 'youth-camp-icmc-2025.firebasestorage.app',
    measurementId: 'G-3EK054DR3T',
  );
}
